apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tw8i2saef-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tw8i2saef-go 
  name: tw8i2saef-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tw8i2saef-go 
